name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Aftman
        uses: ok-nick/setup-aftman@v0.3.0

      - name: Publish Wally package
        run: |
          mkdir -p ~/.wally
          echo "$WALLY_AUTH" > ~/.wally/auth.toml
          wally publish
        env:
          WALLY_AUTH: ${{ secrets.WALLY_AUTH }}

      - name: Build rbxm
        run: |
          wally install
          rojo build -o RoduxUtils.rbxm

      - name: Get version
        id: get_version
        run: echo name="VERSION::${GITHUB_REF#refs/tags/}" >> "${GITHUB_OUTPUT}"

      - name: Generate changelog
        run: lune changelog CHANGELOG.md > latest.md

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ steps.get_version.outputs.VERSION }}
          body_path: latest.md
          fail_on_unmatched_files: true
          files: RoduxUtils.rbxm
